// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkhvniiauprcabtwhdoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJraHZuaWlhdXByY2FidHdoZG96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3NDgzNDcsImV4cCI6MjA1MDMyNDM0N30.8sHMYqYpMsjYNdRfTFYMzF0etd5vDRiLPqHSwGt6c30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);